{
  
    
        "post0": {
            "title": "Assignment 4",
            "content": "Is there life after graduate school? . Download data of Science and Engineering PhDs awarded in the US. Do some analysis in pandas. Make a dashboard visualization of a few interesting aspects of the data . import numpy as np import pandas as pd import dash from dash.dependencies import Input, Output from dash import dcc from dash import html from pandas_datareader import data as web from datetime import datetime as dt import plotly.graph_objs as go #import dash_core_components as dcc #import dash_html_components as html from dash import dcc from dash import html import json import plotly.express as px . The First part of the dashboard is based on Table 1 Doctorate recipients from U.S. colleges and universities: 1958–2017. This dataset can give us a brief idea of the number of Phd awarded each year and the changes in number. . data1 = pd.read_excel(&quot;C:/lucy/Duke/Biostats823/Assignment 4/table1.xlsx&quot;) . data1 = data1.drop([0,1,2]) . data1.columns =[&#39;Year&#39;,&#39;Doctorate Recipients&#39;,&#39;% change from previous year&#39;] . data1.head() . Year Doctorate Recipients % change from previous year . 3 1958 | 8773 | - | . 4 1959 | 9213 | 5 | . 5 1960 | 9733 | 5.6 | . 6 1961 | 10413 | 7 | . 7 1962 | 11500 | 10.4 | . The second part of the dashboard is from Table 12 Doctorate recipients, by major field of study: Selected years, 1987–2017. This dataset demonstrates the number and percentage of doctorate recipents per institute in each subjects of fields from year 1987 to year 2017 . data2_wide = pd.read_csv(&quot;C:/lucy/Duke/Biostats823/Assignment 4/table12_wide.csv&quot;,index_col = 0) . data2_wide.head() . Field_of_Study Category Year Number Percent . 1 Aerospace, aeronautical, and astronautical eng... | Engineering | 1987 | 142 | 0.4 | . 2 Aerospace, aeronautical, and astronautical eng... | Engineering | 1992 | 234 | 0.6 | . 3 Aerospace, aeronautical, and astronautical eng... | Engineering | 1997 | 273 | 0.6 | . 4 Aerospace, aeronautical, and astronautical eng... | Engineering | 2002 | 209 | 0.5 | . 5 Aerospace, aeronautical, and astronautical eng... | Engineering | 2007 | 267 | 0.6 | . The third part of the dashboard is from Table 6 Doctorates awarded, by state or location, broad field of study, and sex of doctorate recipients: 2017. We first read in the dataset and do the data processing part. . data = pd.read_excel(&quot;C:/lucy/Duke/Biostats823/Assignment 4/table6.xlsx&quot; ) . data = data.drop(0) . data.columns = [&quot;State or Location&quot;, &#39;Total_Male&#39;, &#39;Total_Female&#39;, &#39;LifeScience_Male&#39;, &#39;LifeScience_Female&#39;,&#39;Physical_Male&#39;, &#39;Physical_Female&#39;, &#39;Mathematics_Male&#39;, &#39;Mathematics_Female&#39;,&#39;Psychology_Male&#39;,&#39;Psychology_Female&#39;,&#39;Engineering_Male&#39;,&#39;Engineering_Female&#39;,&#39;Education_Male&#39;,&#39;Education_Female&#39;,&#39;Humanities_Male&#39;,&#39;Humanities_Female&#39;,&#39;Other_Male&#39;,&#39;Other_Female&#39;] . data.head() . State or Location Total_Male Total_Female LifeScience_Male LifeScience_Female Physical_Male Physical_Female Mathematics_Male Mathematics_Female Psychology_Male Psychology_Female Engineering_Male Engineering_Female Education_Male Education_Female Humanities_Male Humanities_Female Other_Male Other_Female . 1 United Statesd | 29146 | 25495 | 5629 | 6958 | 4068 | 2011 | 2866 | 976 | 3693 | 5381 | 7389 | 2448 | 1521 | 3300 | 2581 | 2708 | 1399 | 1713 | . 2 Alabama | 365 | 342 | 96 | 92 | 38 | 21 | 35 | 13 | 28 | 61 | 100 | 31 | 34 | 81 | 13 | 15 | 21 | 28 | . 3 Alaska | 19 | 33 | D | D | 9 | 11 | 0 | 0 | D | D | D | D | D | D | 0 | 0 | D | D | . 4 Arizona | 420 | 381 | 57 | 76 | 78 | 32 | 38 | 13 | 53 | 103 | 109 | 32 | 24 | 51 | 41 | 50 | 20 | 24 | . 5 Arkansas | 98 | 104 | 32 | 43 | 6 | 11 | D | D | 8 | 11 | D | D | D | D | 8 | 15 | D | D | . As can be seen from the dataset, the dataset is in state and location level, each column is the number of phd student in specific field, the field includes: Life Science, Physical, Mathematics, Psychology, Engineering, Education, Humanity, Other Field, and each gender is calculated seperately. Thus, for each field, we can add a new column that indicates the total number of phd(female + male). The missing value is denoted as D. . data[&#39;Total_Total&#39;] = data[&#39;Total_Male&#39;] + data[&#39;Total_Female&#39;] data[&#39;LifeScience_Total&#39;] = data[&#39;LifeScience_Male&#39;] + data[&#39;LifeScience_Female&#39;] data[&#39;Physical_Total&#39;] = data[&#39;Physical_Male&#39;] + data[&#39;Physical_Female&#39;] data[&#39;Mathematics_Total&#39;] = data[&#39;Mathematics_Male&#39;] + data[&#39;Mathematics_Female&#39;] data[&#39;Psychology_Total&#39;] = data[&#39;Psychology_Male&#39;] + data[&#39;Psychology_Female&#39;] data[&#39;Engineering_Total&#39;] = data[&#39;Engineering_Male&#39;] + data[&#39;Engineering_Female&#39;] data[&#39;Education_Total&#39;] = data[&#39;Education_Male&#39;] + data[&#39;Education_Female&#39;] data[&#39;Humanities_Total&#39;] = data[&#39;Humanities_Male&#39;] + data[&#39;Humanities_Female&#39;] data[&#39;Other_Total&#39;] = data[&#39;Other_Male&#39;] + data[&#39;Other_Female&#39;] . For the plotting convension, we need to convert the dataset from wide format to long format. . data_long = data.melt(id_vars =&#39;State or Location&#39;, value_name = &#39;Number of People&#39;, var_name = &#39;Fields&#39; ) . data_long[[&#39;Field&#39;,&#39;Subjects&#39;]] = data_long[&#39;Fields&#39;].str.split(&#39;_&#39;, expand=True) . data_long = data_long.drop([&#39;Fields&#39;],axis = 1) . data_long = data_long[[&#39;State or Location&#39;,&#39;Field&#39;,&#39;Subjects&#39;,&#39;Number of People&#39;]] . data_long = data_long[data_long[&#39;Number of People&#39;] != &#39;D&#39; ] . data_long = data_long[data_long[&#39;Number of People&#39;] != &#39;DD&#39; ] . data_long.head() . State or Location Field Subjects Number of People . 0 United Statesd | Total | Male | 29146 | . 1 Alabama | Total | Male | 365 | . 2 Alaska | Total | Male | 19 | . 3 Arizona | Total | Male | 420 | . 4 Arkansas | Total | Male | 98 | . The Field column indicates the specific field of study and Subjects column indicates the female, male or total. . app = dash.Dash() state_filter = data_long[&#39;State or Location&#39;].unique() Timeseries1 = px.line(data1, x=&quot;Year&quot;, y=&quot;Doctorate Recipients&quot;, title=&#39;Number of Recipents from 1958-2017&#39;) Timeseries2 = px.line(data1, x=&quot;Year&quot;, y=&quot;% change from previous year&quot;, title=&#39;% Change in the Number of Recipents from 1958-2017&#39;) app.layout = html.Div([ html.Div([# Page 1 html.Div([ #Subpage 1 #Row 1 (Header) html.Div([ html.Div([ html.H1(&#39;Are there Life after Graduate School&#39;), html.H2(&#39;Dashboard1: Overview of Phd recipients from 1958-2017&#39;, style=dict(color=&#39;#7F90AC&#39;)), ], className = &quot;nine columns padded&quot; ) ], className = &#39;row gs-header gs-text-header&#39;), #Row 2 (Time Series Plot) html.Div([ html.Div([ dcc.Graph(figure = Timeseries1) ],style={&#39;display&#39;: &#39;inline-block&#39;, &#39;width&#39;: &#39;40%&#39;}), html.Div([ dcc.Graph(figure =Timeseries2) ],style={&#39;display&#39;: &#39;inline-block&#39;, &#39;width&#39;: &#39;40%&#39;}), ], className = &#39;row&#39;), ],className = &#39;subpage&#39;), ],className = &#39;page&#39;), html.Div([# Page 2 html.Div([ #Subpage 1 #Row 1 (Header) html.Div([ html.Div([ #html.H1(&#39;Are there Life after Graduate School&#39;), html.H2(&#39;Dashboard2: Doctorate-granting institutions and doctorate recipients per institution: 1973–2017&#39;, style=dict(color=&#39;#7F90AC&#39;)), ], className = &quot;nine columns padded&quot; ) ], className = &#39;row gs-header gs-text-header&#39;), #Row 2 (Time Series Plot) html.Div([ html.Div([ dcc.Graph(id = &#39;TimeSeries Plot3&#39;), dcc.Slider( id=&#39;year-slider&#39;, min=data3_wide[&#39;Year&#39;].min(), max=data3_wide[&#39;Year&#39;].max(), value=data3_wide[&#39;Year&#39;].min(), marks={str(year): str(year) for year in data3_wide[&#39;Year&#39;].unique()}, step=None ) ],style={&#39;display&#39;: &#39;inline-block&#39;, &#39;width&#39;: &#39;40%&#39;}), ], className = &#39;row&#39;), ],className = &#39;subpage&#39;), ],className = &#39;page&#39;), html.Div([ # page 3 html.A([ &#39;Print PDF&#39; ], className=&quot;button no-print&quot;, style=dict(position=&quot;absolute&quot;, top=-40, right=0)), html.Div([ # subpage 1 # Row 1 (Header) html.Div([ html.Div([ #html.H1(&#39;Are there Life after Graduate School&#39;), html.H2(&#39;Dashboard3: The distribution of the number of Phd across Fields and Gender in the US&#39;, style=dict(color=&#39;#7F90AC&#39;)), ], className = &quot;nine columns padded&quot; ) ], className = &quot;row gs-header gs-text-header&quot;), html.Br([]), # Row 2 html.Div([ # Create a dropdown list html.Div([ dcc.Dropdown( id=&#39;state_filter&#39;, options=[{&#39;label&#39;: i, &#39;value&#39;: i} for i in state_filter], value=&#39;North Carolina&#39; ) ], style={&#39;width&#39;: &#39;40%&#39;, &#39;display&#39;: &#39;inline-block&#39;},className = &#39;four columns&#39;), ],className = &#39;row&#39;), # Row 3 Create two bar plots html.Div([ html.Div([ dcc.Graph( id=&#39;crossfilter-indicator-barplot&#39;, hoverData={&#39;points&#39;: [{&#39;customdata&#39;: &#39;Other&#39;}]} ) ], style={&#39;width&#39;: &#39;49%&#39;, &#39;display&#39;: &#39;inline-block&#39;},className = &#39;four columns&#39;), html.Div([ dcc.Graph(id=&#39;Field_by_gender&#39;), ], style={&#39;display&#39;: &#39;inline-block&#39;, &#39;width&#39;: &#39;40%&#39;}), ],className = &#39;row&#39;) ],className = &quot;subpage&quot;), ], className = &quot;page&quot; ) ]) @app.callback( dash.dependencies.Output(&#39;TimeSeries Plot3&#39;, &#39;figure&#39;), dash.dependencies.Input(&#39;year-slider&#39;, &#39;value&#39;)) def update_figure(selected_year): data2_new = data2_wide[data2_wide.Year == selected_year] fig = px.scatter(data2_new, x=&quot;Percent&quot;, y=&quot;Number&quot;,size = &#39;Percent&#39;, color=&quot;Category&quot;, hover_name=&quot;Field_of_Study&quot;, log_x=True, size_max=30) fig.update_layout(transition_duration=500) return fig @app.callback( dash.dependencies.Output(&#39;crossfilter-indicator-barplot&#39;, &#39;figure&#39;), dash.dependencies.Input(&#39;state_filter&#39;, &#39;value&#39;)) def update_graph(selected_states): Total_only_df = data_long[data_long[&#39;Subjects&#39;] == &#39;Total&#39;] filtered_df = Total_only_df[Total_only_df[&#39;State or Location&#39;] == selected_states] colors = px.colors.qualitative.Pastel2 return { &#39;data&#39;:[go.Bar( x = filtered_df[&#39;Field&#39;], y = filtered_df[&#39;Number of People&#39;], text = filtered_df[&#39;Field&#39;], customdata = filtered_df[&#39;Field&#39;], marker_color=colors )], &#39;layout&#39;: go.Layout( xaxis={ &#39;title&#39;: &#39;Field&#39; }, yaxis={ &#39;title&#39;: &#39;Number of People&#39; }, height = 450, hovermode = &#39;closest&#39;, title = &#39;Total Number of Phd by Fields&#39; ) } def create_barchart(dff, title): colors = [px.colors.qualitative.Pastel1[1],px.colors.qualitative.Set1[1] ] return { &#39;data&#39;:[go.Bar( x = dff[&#39;Subjects&#39;], y = dff[&#39;Number of People&#39;], text = dff[&#39;Subjects&#39;], customdata = dff[&#39;Subjects&#39;], marker_color = colors )], &#39;layout&#39;: go.Layout( xaxis={ &#39;title&#39;: &#39;Gender&#39; }, yaxis={ &#39;title&#39;: &#39;Number of People&#39; }, height = 450, hovermode = &#39;closest&#39;, title = &#39;Number of Female and Male Phd for Specific Field&#39; ) } @app.callback( dash.dependencies.Output(&#39;Field_by_gender&#39;, &#39;figure&#39;), [dash.dependencies.Input(&#39;crossfilter-indicator-barplot&#39;, &#39;hoverData&#39;), dash.dependencies.Input(&#39;state_filter&#39;, &#39;value&#39;)]) def update_create_barchart(hoverData, selected_states): field_name = hoverData[&#39;points&#39;][0][&#39;customdata&#39;] dff = data_long[data_long[&#39;Field&#39;] == field_name] dff = dff[dff[&#39;State or Location&#39;] == selected_states] dff = dff[dff[&#39;Subjects&#39;] != &#39;Total&#39;] title = &#39;Field by Gender&#39; return create_barchart(dff, title) app.css.append_css({ &#39;external_url&#39;: &#39;https://codepen.io/chriddyp/pen/bWLwgP.css&#39; }) if __name__ == &#39;__main__&#39;: app.run_server() . Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ Dash is running on http://127.0.0.1:8050/ * Serving Flask app &#39;__main__&#39; (lazy loading) * Environment: production WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead. * Debug mode: off . * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit) C: Users lucylin Anaconda3 lib site-packages dash resources.py:72: UserWarning: You have set your config to `serve_locally=True` but A local version of https://codepen.io/chriddyp/pen/bWLwgP.css is not available. If you added this file with `app.scripts.append_script` or `app.css.append_css`, use `external_scripts` or `external_stylesheets` instead. See https://dash.plotly.com/external-resources 127.0.0.1 - - [21/Oct/2021 17:24:09] &#34;GET / HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-layout HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-dependencies HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:10] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:11] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:17] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - . Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above . C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py:775: RuntimeWarning: invalid value encountered in greater_equal C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py:775: RuntimeWarning: invalid value encountered in less_equal 127.0.0.1 - - [21/Oct/2021 17:24:28] &#34;POST /_dash-update-component HTTP/1.1&#34; 500 - 127.0.0.1 - - [21/Oct/2021 17:24:30] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:32] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:36] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:42] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:42] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:43] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:44] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:45] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:46] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:47] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:24:47] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:27:03] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:02] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - . Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above Exception on /_dash-update-component [POST] Traceback (most recent call last): File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 2073, in wsgi_app response = self.full_dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &#34;C: Users lucylin Anaconda3 lib site-packages flask app.py&#34;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &#34;C: Users lucylin Anaconda3 lib site-packages dash dash.py&#34;, line 1336, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File &#34;C: Users lucylin Anaconda3 lib site-packages dash _callback.py&#34;, line 151, in add_context output_value = func(*func_args, **func_kwargs) # %% callback invoked %% File &#34;&lt;ipython-input-114-188d2872db7b&gt;&#34;, line 115, in update_figure log_x=True, size_max=30) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _chart_types.py&#34;, line 66, in scatter return make_figure(args=locals(), constructor=go.Scatter) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly express _core.py&#34;, line 2114, in make_figure trace.update(patch) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5084, in update BaseFigure._perform_update(self, dict1, overwrite=overwrite) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3900, in _perform_update BaseFigure._perform_update(plotly_obj[key], val) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 3921, in _perform_update plotly_obj[key] = val File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 4819, in __setitem__ self._set_prop(prop, value) File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5163, in _set_prop raise err File &#34;C: Users lucylin Anaconda3 lib site-packages plotly basedatatypes.py&#34;, line 5158, in _set_prop val = validator.validate_coerce(val) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 785, in validate_coerce self.raise_invalid_elements(some_invalid_els) File &#34;C: Users lucylin Anaconda3 lib site-packages _plotly_utils basevalidators.py&#34;, line 314, in raise_invalid_elements valid_clr_desc=self.description(), ValueError: Invalid element(s) received for the &#39;size&#39; property of scatter.marker Invalid elements include: [nan] The &#39;size&#39; property is a number and may be specified as: - An int or float in the interval [0, inf] - A tuple, list, or one-dimensional numpy array of the above . 127.0.0.1 - - [21/Oct/2021 17:28:05] &#34;POST /_dash-update-component HTTP/1.1&#34; 500 - 127.0.0.1 - - [21/Oct/2021 17:28:07] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:11] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:11] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:11] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:13] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:13] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:16] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:17] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:17] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - 127.0.0.1 - - [21/Oct/2021 17:28:19] &#34;POST /_dash-update-component HTTP/1.1&#34; 200 - . Below is the demo for the dashboard . From Dashboard 1, we can see that the number of doctorate recipents is overall increasing, especially between 1960s and 1970s, the number almost triple. It may be possible that more and more students are willing to pursue the phd degree or it is possible that more and more students attend the universities. As for the % change in the number of phds, between 1960s and 1970s, the perentage change is very large. There are several years when the number actually decreases, such as year 1977, 1999, 2010. . . Dashboard 2 is a time series plot with year slider, it demonstates the scatter plot of the number of Phds and the percentage of Phds for each subjects of fields across the year. . Dashboard3 is actually an interactive plot, the two bar plot are linked with each other. When you select a state, the left bar plot will show the number of doctortate recipents for each fields, and when you click on a specific field, the right bar plot will demonstrate the number of male and female doctorate recipents for that field. From the dashboard, we can see that there are usually more male phds than female phds in engineering fields such as Physics, Mathematics, Engineering, and there are usually more female phds than male phds in fields such as Psychology, Humanity, Education. .",
            "url": "https://lucylin1997.github.io/fastpage_copy/jupyter/2021/10/21/Assignment4-Yili-Lin.html",
            "relUrl": "/jupyter/2021/10/21/Assignment4-Yili-Lin.html",
            "date": " • Oct 21, 2021"
        }
        
    
  
    
        ,"post1": {
            "title": "Assignment 3",
            "content": "The plotting library I choose is Altair. The reason is that: . The interactive plot created by ipywidgets cannot be displayed in the fastpage, as is shown in the forum: link here and it is also not easy to put plotly figures in the fastpage blog. . | Altair also offers a variety of interactive options with sliders and dropdowns, which can make the plot more vivid etc. . | . import pandas as pd import altair as alt from vega_datasets import data . Task 1 . The first dataset is about the malaria deaths by country for all ages across the world and time. The entity is the full country name, the code column is the ISO3166 code. The head of the data is shown below. Considering that the data contains countries and time, the first plot we can consider is the map plot with a time slider. . df = pd.read_csv(&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-13/malaria_deaths.csv&#39;) df.head() . Entity Code Year Deaths - Malaria - Sex: Both - Age: Age-standardized (Rate) (per 100,000 people) . 0 Afghanistan | AFG | 1990 | 6.802930 | . 1 Afghanistan | AFG | 1991 | 6.973494 | . 2 Afghanistan | AFG | 1992 | 6.989882 | . 3 Afghanistan | AFG | 1993 | 7.088983 | . 4 Afghanistan | AFG | 1994 | 7.392472 | . In order to draw a map plot in altair, we need to add the country code to the original dataset so that we can map the countries into the world map. The country_info dataset contains full infomartion about each country, including the FIFA code, ISO3166 code etc. . country_info = pd.read_csv(&quot;https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv&quot;,dtype = &#39;str&#39;) country_info.head() . FIFA Dial ISO3166-1-Alpha-3 MARC is_independent ISO3166-1-numeric GAUL FIPS WMO ISO3166-1-Alpha-2 ... Sub-region Name official_name_ru Global Name Capital Continent TLD Languages Geoname ID CLDR display name EDGAR . 0 TPE | 886 | TWN | ch | Yes | 158 | 925 | TW | | TW | ... | NaN | NaN | NaN | Taipei | AS | .tw | zh-TW,zh,nan,hak | 1668284 | Taiwan | NaN | . 1 AFG | 93 | AFG | af | Yes | 004 | 1 | AF | AF | AF | ... | Southern Asia | Афганистан | World | Kabul | AS | .af | fa-AF,ps,uz-AF,tk | 1149361 | Afghanistan | B2 | . 2 ALB | 355 | ALB | aa | Yes | 008 | 3 | AL | AB | AL | ... | Southern Europe | Албания | World | Tirana | EU | .al | sq,el | 783754 | Albania | B3 | . 3 ALG | 213 | DZA | ae | Yes | 012 | 4 | AG | AL | DZ | ... | Northern Africa | Алжир | World | Algiers | AF | .dz | ar-DZ | 2589581 | Algeria | B4 | . 4 ASA | 1-684 | ASM | as | Territory of US | 016 | 5 | AQ | | AS | ... | Polynesia | Американское Самоа | World | Pago Pago | OC | .as | en-AS,sm,to | 5880801 | American Samoa | B5 | . 5 rows × 56 columns . We can do some data transformation to the original malaria death dataset and filter out the country that are in the country_info dataset . df.columns = [&#39;name&#39;, &#39;ISO3166-1-Alpha-3&#39;,&#39;Year&#39;,&#39;Death_Rate&#39;] # Change the column name to make the name of two datasets more consistent. df_new = df[df[&#39;ISO3166-1-Alpha-3&#39;].isin(country_info[&#39;ISO3166-1-Alpha-3&#39;])] # check whether the country exists in the country_info dataset df_new.head() . name ISO3166-1-Alpha-3 Year Death_Rate . 0 Afghanistan | AFG | 1990 | 6.802930 | . 1 Afghanistan | AFG | 1991 | 6.973494 | . 2 Afghanistan | AFG | 1992 | 6.989882 | . 3 Afghanistan | AFG | 1993 | 7.088983 | . 4 Afghanistan | AFG | 1994 | 7.392472 | . Merge the two dataset and exclude irrelevant columns . df_final = pd.merge(df_new, country_info , on = &#39;ISO3166-1-Alpha-3&#39;, how = &#39;left&#39;) df_final = df_final[[&#39;name&#39;,&#39;Year&#39;,&#39;Death_Rate&#39;,&#39;ISO3166-1-numeric&#39;]] df_final.head() . name Year Death_Rate ISO3166-1-numeric . 0 Afghanistan | 1990 | 6.802930 | 004 | . 1 Afghanistan | 1991 | 6.973494 | 004 | . 2 Afghanistan | 1992 | 6.989882 | 004 | . 3 Afghanistan | 1993 | 7.088983 | 004 | . 4 Afghanistan | 1994 | 7.392472 | 004 | . df_final.head() . name Year Death_Rate ISO3166-1-numeric . 0 Afghanistan | 1990 | 6.802930 | 004 | . 1 Afghanistan | 1991 | 6.973494 | 004 | . 2 Afghanistan | 1992 | 6.989882 | 004 | . 3 Afghanistan | 1993 | 7.088983 | 004 | . 4 Afghanistan | 1994 | 7.392472 | 004 | . Set the slider . alt.data_transformers.disable_max_rows() #The default row that altair can take is 5000, we need to specify the disable_max_rows if the rows are over 5000 countries = alt.topo_feature(data.world_110m.url, &#39;countries&#39;) # Set the silder, step = 1, min year is 1990, max year is 2016 slider = alt.binding_range( step=1, min=1990, max=2016 ) select_date = alt.selection_single( name=&quot;Slider&quot;, fields=[&#39;Year&#39;], bind=slider, ) . alt.Chart(df_final).mark_geoshape() .encode(color=&#39;Death_Rate:Q&#39;) .add_selection(select_date) .transform_filter(select_date) .transform_lookup( lookup=&#39;ISO3166-1-numeric&#39;, from_=alt.LookupData(countries, key=&#39;id&#39;, fields=[&quot;type&quot;, &quot;properties&quot;, &quot;geometry&quot;]) ) .project(&#39;equirectangular&#39;) .properties( width=400, height=300, title=&#39;Malaria Death Rate (per 100,000 people) &#39; ) . From the above map plot, we can see that most of the countries have death rate less than 50 per 100,000 people, countries with high malaria death rate are more likely to be in Afirica and as time goes by, the death rate continues to decrease. However, one problem with this plot may be that we cannot tell the trend of a single country, it is difficult to distinguish each country. Another plot we can try is the line chart with country as dropdown list. . df_final[&#39;Year&#39;] = pd.to_datetime(df_final[&#39;Year&#39;], format=&#39;%Y&#39;) #Change the year to datetime type country_list = df_final[&#39;name&#39;].dropna().unique() country_list = country_list.tolist() dropdown = alt.binding_select( options = country_list ) select_country = alt.selection_single( name=&quot;dropdown&quot;, fields=[&#39;name&#39;], bind = dropdown, ) alt.Chart(df_final).mark_line().encode( x=&#39;Year&#39;, y=&#39;Death_Rate&#39;, ).add_selection( select_country ).transform_filter( select_country ).properties( width = 500, height=400, title=f&#39;Malaria Death Rate for a singe country (per 100,000 people)&#39; ).configure_axis( grid=False ) . From the line plot, we can see how the death rate of each country change over time. . Task 2 . The second dataset is about the malaria incidence by country for all ages across the world and time. The entity is the full country name, the code column is the ISO3166 code. The head of the data is shown below. . df1 = pd.read_csv(&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-13/malaria_inc.csv&#39;) df1.head() . Entity Code Year Incidence of malaria (per 1,000 population at risk) (per 1,000 population at risk) . 0 Afghanistan | AFG | 2000 | 107.100000 | . 1 Afghanistan | AFG | 2005 | 46.500000 | . 2 Afghanistan | AFG | 2010 | 23.900000 | . 3 Afghanistan | AFG | 2015 | 23.600000 | . 4 Algeria | DZA | 2000 | 0.037746 | . We can do some data transformation to the original malaria incidence dataset and filter out the country that are in the country_info dataset . df1.columns = [&#39;name&#39;, &#39;ISO3166-1-Alpha-3&#39;,&#39;Year&#39;,&#39;Incidence_Rate&#39;] df1_new = df1[df1[&#39;ISO3166-1-Alpha-3&#39;].isin(country_info[&#39;ISO3166-1-Alpha-3&#39;])] df1_new.head() . name ISO3166-1-Alpha-3 Year Incidence_Rate . 0 Afghanistan | AFG | 2000 | 107.100000 | . 1 Afghanistan | AFG | 2005 | 46.500000 | . 2 Afghanistan | AFG | 2010 | 23.900000 | . 3 Afghanistan | AFG | 2015 | 23.600000 | . 4 Algeria | DZA | 2000 | 0.037746 | . df1_final = pd.merge(df1_new, country_info , on = &#39;ISO3166-1-Alpha-3&#39;, how = &#39;left&#39;) df1_final = df1_final[[&#39;name&#39;,&#39;Year&#39;,&#39;Incidence_Rate&#39;,&#39;ISO3166-1-numeric&#39;]] df1_final.head() . name Year Incidence_Rate ISO3166-1-numeric . 0 Afghanistan | 2000 | 107.100000 | 004 | . 1 Afghanistan | 2005 | 46.500000 | 004 | . 2 Afghanistan | 2010 | 23.900000 | 004 | . 3 Afghanistan | 2015 | 23.600000 | 004 | . 4 Algeria | 2000 | 0.037746 | 012 | . alt.data_transformers.disable_max_rows() countries = alt.topo_feature(data.world_110m.url, &#39;countries&#39;) slider1 = alt.binding_range( step=5, min=2000, max=2015 ) select_date1 = alt.selection_single( name=&quot;slider&quot;, fields=[&#39;Year&#39;], bind=slider1, ) . alt.Chart(df1_final).mark_geoshape() .encode(color=&#39;Incidence_Rate:Q&#39;) .add_selection(select_date1) .transform_filter(select_date1) .transform_lookup( lookup=&#39;ISO3166-1-numeric&#39;, from_=alt.LookupData(countries, key=&#39;id&#39;, fields=[&quot;type&quot;, &quot;properties&quot;, &quot;geometry&quot;]) ) .project(&#39;equirectangular&#39;) .properties( width=400, height=300, title=&#39;Malaria Incidence Rate (per 1,000 people) &#39; ) . df1_final[&#39;Year&#39;] = pd.to_datetime(df1_final[&#39;Year&#39;], format=&#39;%Y&#39;) #Change the year to datetime type country_list1 = df1_final[&#39;name&#39;].dropna().unique() country_list1 = country_list1.tolist() dropdown1 = alt.binding_select( options = country_list1 ) select_country1 = alt.selection_single( name=&quot;dropdown&quot;, fields=[&#39;name&#39;], bind = dropdown1, ) alt.Chart(df1_final).mark_line().encode( x=&#39;Year&#39;, y=&#39;Incidence_Rate&#39;, ).add_selection( select_country1 ).transform_filter( select_country1 ).properties( width = 500, height=400, title=f&#39;Malaria Incidence Rate for a singe country (per 1,000 people)&#39; ).configure_axis( grid=False ) . Task 3 . The third dataset is about the malaria deathe by country for all ages across the world and time. The entity is the full country name, the code column is the ISO3166 code. The head of the data is shown below.Malaria deaths by age across the world and time . df2 = pd.read_csv(&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-13/malaria_deaths_age.csv&#39;) df2.head() . Unnamed: 0 entity code year age_group deaths . 0 1 | Afghanistan | AFG | 1990 | Under 5 | 184.606435 | . 1 2 | Afghanistan | AFG | 1991 | Under 5 | 191.658193 | . 2 3 | Afghanistan | AFG | 1992 | Under 5 | 197.140197 | . 3 4 | Afghanistan | AFG | 1993 | Under 5 | 207.357753 | . 4 5 | Afghanistan | AFG | 1994 | Under 5 | 226.209363 | . df2.columns = [&#39;index&#39;,&#39;name&#39;, &#39;ISO3166-1-Alpha-3&#39;,&#39;Year&#39;,&#39;Age_Group&#39;,&#39;Death_Rate&#39;] df2_new = df2[df2[&#39;ISO3166-1-Alpha-3&#39;].isin(country_info[&#39;ISO3166-1-Alpha-3&#39;])] df2_new.head() . index name ISO3166-1-Alpha-3 Year Age_Group Death_Rate . 0 1 | Afghanistan | AFG | 1990 | Under 5 | 184.606435 | . 1 2 | Afghanistan | AFG | 1991 | Under 5 | 191.658193 | . 2 3 | Afghanistan | AFG | 1992 | Under 5 | 197.140197 | . 3 4 | Afghanistan | AFG | 1993 | Under 5 | 207.357753 | . 4 5 | Afghanistan | AFG | 1994 | Under 5 | 226.209363 | . df2_final = pd.merge(df2_new, country_info , on = &#39;ISO3166-1-Alpha-3&#39;, how = &#39;left&#39;) df2_final = df2_final[[&#39;name&#39;,&#39;Year&#39;,&#39;Death_Rate&#39;,&#39;ISO3166-1-numeric&#39;,&#39;Age_Group&#39;]] df2_final.head() . name Year Death_Rate ISO3166-1-numeric Age_Group . 0 Afghanistan | 1990 | 184.606435 | 004 | Under 5 | . 1 Afghanistan | 1991 | 191.658193 | 004 | Under 5 | . 2 Afghanistan | 1992 | 197.140197 | 004 | Under 5 | . 3 Afghanistan | 1993 | 207.357753 | 004 | Under 5 | . 4 Afghanistan | 1994 | 226.209363 | 004 | Under 5 | . The plot I choose is the line plot with dropdown, different color represent different age group. So based on this plot, we can see the trend of death rate of different countries for different age group. . df2_final[&#39;Year&#39;] = pd.to_datetime(df2_final[&#39;Year&#39;], format=&#39;%Y&#39;) country_list2 = df2_final[&#39;name&#39;].dropna().unique() country_list2 = country_list2.tolist() dropdown2 = alt.binding_select( options = country_list2 ) select_country2 = alt.selection_single( name=&quot;dropdown&quot;, fields=[&#39;name&#39;], bind = dropdown2, ) alt.Chart(df2_final).mark_point().encode( x=&#39;Year&#39;, y=&#39;Death_Rate&#39;, color = &#39;Age_Group&#39; ).add_selection( select_country2 ).transform_filter(select_country2) .",
            "url": "https://lucylin1997.github.io/fastpage_copy/jupyter/2021/09/30/Assignment3.html",
            "relUrl": "/jupyter/2021/09/30/Assignment3.html",
            "date": " • Sep 30, 2021"
        }
        
    
  
    
        ,"post2": {
            "title": "Assignment 2",
            "content": "import numpy as np import pandas as pd from decimal import * import math import unittest from sympy import * . Find the first 10-digit prime in the decimal expansion of $17 pi$ . The first 5 digits in the decimal expansion of $ pi$ are 14159. The first 4-digit prime in the decimal expansion of $ pi$ are 4159. You are asked to find the first 10-digit prime in the decimal expansion of $17 pi$. . Task 1: Write a function to generate an arbitrary large expansion of a mathematical expression like $ pi$. . The 3rd party library sympy has a function called N(expr, &lt;args&gt;) that allows us to directly expand the expression to a certain precision. . &gt;&gt; N(pi, 5) 3.1416 . def generate_expansion(precision, expression): &quot;&quot;&quot; This function returns an expansion of a mathematical expression given the precision. &quot;&quot;&quot; return N(expression, precision) . &gt;&gt; a = generate_expansion(5, pi) &gt;&gt; a 3.1416 &gt;&gt; type(a) sympy.core.numbers.Float . Then we can run a unit test to test the generate_expansion function | . class TestNotebook(unittest.TestCase): def test_genexp(self): self.assertEqual(str(generate_expansion(10, pi)), &#39;3.141592654&#39;) unittest.main(argv=[&#39;&#39;], verbosity=2, exit=False) . test_genexp (__main__.TestFunc) ... ok test_genexp (__main__.TestNotebook) ... ok - Ran 2 tests in 0.002s OK . &lt;unittest.main.TestProgram at 0x23203530ca0&gt; . Task 2: Write a function to check if a number is a prime number . Based on the definition of prime number, we need to check whether the number can be divided by any number that is less than the square root of the certain number. | . def is_prime(num): &quot;&quot;&quot; The function returns whether a given number is prime or not &quot;&quot;&quot; if num &gt; 1: for i in range(2, int(math.sqrt(num))+1): if (num % i) == 0: return False #break return True . &gt;&gt; is_prime(40) False . Then we can run a unit test to test the is_prime function | . class TestNotebook(unittest.TestCase): def test_isprime(self): self.assertEqual(is_prime(29), True) # 29 is a prime number self.assertEqual(is_prime(30), False) # 30 is not a prime number unittest.main(argv=[&#39;&#39;], verbosity=2, exit=False) . test_genexp (__main__.TestFunc) ... ok test_isprime (__main__.TestNotebook) ... ok - Ran 2 tests in 0.005s OK . &lt;unittest.main.TestProgram at 0x2320352b910&gt; . Task 3: Slicing Window . def slicing_window (number_str, idx): &quot;&quot;&quot; The function returns the specified width from a long iterable, the inputs are the string format of a number and the start point of the number &quot;&quot;&quot; return int(number_str[idx: idx+10]) . The slicing_window works like below . &gt;&gt; slicing_window(&#39;12345678899443878169846&#39;,1) 2345678899 . Then we can run a unit test to test the slicing_window function | . class TestNotebook(unittest.TestCase): def test_slicingwindow(self): self.assertEqual(slicing_window(&#39;12345667788990&#39;,2), 3456677889) unittest.main(argv=[&#39;&#39;], verbosity=2, exit=False) . test_genexp (__main__.TestFunc) ... ok test_slicingwindow (__main__.TestNotebook) ... ok - Ran 2 tests in 0.003s OK . &lt;unittest.main.TestProgram at 0x23203542760&gt; . def find_prime(precision, expression): &quot;&quot;&quot;The function returns the first 10-digit number in the expansion of the expression &quot;&quot;&quot; expansion = generate_expansion(precision, expression) formula = str(expansion) # The output of the generate_expansion is float, we need to convert it to string first string = formula.replace(&quot;.&quot;, &quot;&quot;) # replace the decimal point in the expansion #initial = False for idx in range(len(string)): if is_prime(slicing_window(string, idx)) is True: print( f&#39;The first 10-digit prime of {expression} is {slicing_window(string, idx)} and the start point is at {idx}&#39;) return slicing_window(string, idx) break . Then we can run a unit test to test the find_prime function | . class TestNotebook(unittest.TestCase): def test_slicingwindow(self): self.assertEqual(find_prime(500, exp(1)), 7427466391) unittest.main(argv=[&#39;&#39;], verbosity=2, exit=False) . test_genexp (__main__.TestFunc) ... ok test_slicingwindow (__main__.TestNotebook) ... . The first 10-digit prime of E is 7427466391 and the start point is at 99 . ok - Ran 2 tests in 0.015s OK . &lt;unittest.main.TestProgram at 0x23203542b20&gt; . The the final solution to the problem is: | . find_prime(500, 17*pi) . The first 10-digit prime of 17*pi is 8649375157 and the start point is at 20 . 8649375157 .",
            "url": "https://lucylin1997.github.io/fastpage_copy/jupyter/2021/09/17/Assignment2_Yili-Lin.html",
            "relUrl": "/jupyter/2021/09/17/Assignment2_Yili-Lin.html",
            "date": " • Sep 17, 2021"
        }
        
    
  
    
        ,"post3": {
            "title": "Assignment 1",
            "content": "Question 1 Problem 15 Lattice Path . Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner. . . How many such routes are there through a 20×20 grid? . Solution to Question 1 . We can first consider the grid as a matrix, each element in the matrix represents the number of routes to that a location in the grid. For example, for a 2×2 grid, the corresponding matrix ${a_{i,j}}$ looks like this: $$ left( begin{array}{l} 0&amp; 1 &amp; 1 1&amp; 2&amp;3 1&amp; 3 &amp;6 end{array} right) $$ $a_{2,2}=6$, meaning that there are 6 routes to the bottom right corner. From the $2 times 2$ grid example and our observation, we find that there is always only one route for those located on the left and top of the grid. And for the remaining locations, the number of routes depend on those located on its top and left. So it is a dynamic programming problem. . import numpy as np def count_path(n): &quot;&quot;&quot;The parameter of the function is the dimension of the grid and it will return the number of routes to the bottom right corner of the grid &quot;&quot;&quot; # Dynamic Programming # Initilize the condition boundary mat = np.zeros((n+1, n+1)) for idx in range(len(mat)): mat[0][idx] = 1 # The top boundary of the grid only has one routes mat[idx][0] = 1 # The left boundary of the grid has only one routes for row in range(1, len(mat)): #dynamic programming for col in range(1, len(mat)): mat[row, col] = mat[row, col-1] + mat[row-1, col] return mat[n][n] #return the location on the bottom right corner if __name__ == &#39;__main__&#39;: print(count_path(20)) . 137846528820.0 . Question 2 Problem 50 Distinct Prime Factors . The prime 41, can be written as the sum of six consecutive primes: 41 = 2 + 3 + 5 + 7 + 11 + 13 This is the longest sum of consecutive primes that adds to a prime below one-hundred. . The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953. . Which prime, below one-million, can be written as the sum of the most consecutive primes? . Solution to Question 2 . First, we need to generate a list of prime number. There is a traditional algorithm called sieve of eratosthenes, which is designed for generating prime numbers less than a given value. . Sieve of Eratosthenes . Create a list of n-1 consecutive integers 2, 3, 4,..., n. 2 is the smallest prime number | For the first loop, set k to 2 | Let k increase k every step until it reaches n, that is, the algorithm loop over k, 2k, 3k,.. and mark these numbers in the list | Then find the smallest number in the list that is not marked and if no such number exists, the algorithm will stop. Otherwise, set k to the new number and iterate again. | At the end of the algorithm, all the numbers that are not marked are the prime numbers.Example:Find prime less than 20 &gt; List all the number that is less than 20 . 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 . Start with 2, we will mark 2, 4, 6,.. 20 . 2, 3, 5, 7, 9, 11, 13, 15, 17, 19 . The next start number is 3, we will mark 9,15 . 2, 3, 5, 7, 11, 13, 17, 19 . Then we can see that all the prime numbers less than 20 are listed in the above. . | With the sieve of eratosthenes algorithm, we can find all the prime numbers that are less than the given limit. When the limit is 100, the prime list is [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]. For the first loop, We start with the first prime number 2, and we will loop over the whole prime list to check if 2, 2 + 3, 2 + 3 + 5... is a prime number and if the summation exceeds 100. When the summation is a prime number, the current length of the consective prime numbers is the difference between the index of the first number and the last number, and if the summation exceeds 100, the stop index is the index of the last number. In this case, 2 + 3 + 5 + 7+ 11 + 13 + 17 + 19 + 23 = 100, so the stop index should be 9. Since 2 + 3 + 5 + 7+ 11 + 13= 41 is the longest sum of consecutive prime for the first loop, the length of consecutive after first loop is 6. Similarly we start with prime number 3, 5,.... until the algorithm stops. . import numpy as np import math def sieve_func(n): bool_list = [True] * n #This is the list used to indicate whether the number is marked, initially set all the elements to True bool_list[0] = False # 0 is not a prime number bool_list[1] = False # 1 is not a prime number for i in range(2, int(math.sqrt(n))+1): if bool_list[i] is True: for j in range(i**2, n, i): bool_list[j] = False prime_list = [index for index, boolvalue in enumerate(bool_list) if boolvalue == True] # find all the numbers that are not marked return prime_list . def find_distinct_factor(limit): &quot;&quot;&quot; The parameter of this function is the limit value, and the function will return the largest prime that can be written as the sum of the most consecutive primes under the given limit &quot;&quot;&quot; primes = sieve_func(limit) # Set the original length of the consecutive number to be 0 raw_length = 0 # initial value of the consecutive prime sum largest_sum = 0 # the last index for the end of the consecutive number, that is, if the index of the prime in the list exceeds this number, the summation will be larger than the given value # Initially set to the length of the prime list last_idx = len(primes) # two for loops for i in range(len(primes)): for j in range(i + raw_length, last_idx): summation = sum(primes[i:j]) if summation &lt; limit: if summation in primes: raw_length = j - i largest_sum = summation else: # When the summation of the consecutive number exceeds 100, we will set the stop point last_idx = j + 1 break return largest_sum . print(find_distinct_factor(1000000)) . 997651 . Question 3 Problem 123 Prime square remainders . Let $p_n$ be the nth prime: 2, 3, 5, 7, 11,... and let r be the reminder when $(p_n-1)^n + (p_n+1)^n$ is divided by $p_n^2$. . For example, when n = 3, $p_3 =5$, and $4^3 + 6^3 = 280 = 5 mod 25$. . The least value of n for which the reminder first exceeds $10^9$ is 7037. . Find the least value of n for which the reminder first exceeds $10^{10}$. . Solution to Question 3 . The expansion of $(p_n-1)^n$: . $(p_n-1)^n = p_n^n - (n-1)p_n^{n-1}+ binom{n}{n-2}p_n^{n-2}+...+(-1)^{n-1}np_n+(-1)^n$. . The expansion of $(p_n+1)^n$ is: . $(p_n+1)^n= p_n^n+ (n-1)p_n^{n-1}+ binom{n}{n-2}p_n^{n-2}+...+np_n+ 1$. . From the equation above we know that except for the last two terms, all the other terms are divisable by $p_n^2$. Thus, the reminder when $(p_n-1)^n+(p_n+1)^n$ is divided by $p_n^2$ should be: . $r = (-1)^{n-1}np_n+(-1)^n +np_n+1$. . So when n is an odd value, $r = 2np_n$, when n is an even number, $r= 2$. The question requires us to find the least value of n for which the reminder first exceeds $10^{10}$, so n must be an odd number. As is mentioned in the problem description: &quot;the least value of n for which the remainder first exceeds $10^9$ is 7037&quot;, thus the start point can begin with 7037 and we only care about the odd number. We can use the sieve function we defined in Question 2 and list all the prime number which is less than 5000000 (This number does not need to be exact 5000000, we just need to define a large number to make sure that there are enough prime numbers). Then we can loop over the prime number and find the least value of n when the reminder exceeds $10^{10}$ . def find_reminder(n): &quot;&quot;&quot; The find_reminder() function has one parameter n, which is the limit. The function will return the least value of n when the reminder exceeds the given limit. &quot;&quot;&quot; initial_n = 7037 #Set the initial value of n to 7037 limit = n #max limit for the reminder product = 0 primeslist = sieve_func(5_000_000) # Find all the prime number which is less than 5_000_000, the limit can vary while product &lt;= limit: initial_n += 2 product = 2 * initial_n * primeslist[initial_n-1] return initial_n if __name__ == &#39;__main__&#39;: print(find_reminder(10000000000)) . 21035 .",
            "url": "https://lucylin1997.github.io/fastpage_copy/jupyter/2021/09/01/Assignment1.html",
            "relUrl": "/jupyter/2021/09/01/Assignment1.html",
            "date": " • Sep 1, 2021"
        }
        
    
  

  
  

  
      ,"page1": {
          "title": "About Me",
          "content": "Profile . Lucy Lin, a devoted and meticulous Master of Biostatistics candidate from Duke University with a solid background in mathematics and statistics, enthusiastic about the application of electronic health data in providing better health care to patients. Currently seeking an internship in Biostatistics/Data Science. Education . Duke University, School of Medicine . Master of Biostatistics &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Aug,2020 - May, 2022 . Relevant courses: Introduction to Statistical Theory and Methods I and II, Applied Biostatistics Methods I and II, Introduction to Practice of Biostatistics I and II, Introduction to Statistical Programming I and II, Software Tools for Data Science. . Shanghai University of Finance and Economics . Information and Computing Science &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Sep,2016 - Jun,2020 . Revelent courses: Data Structure, Big Data Process, Statistical Computing, Time series Analysis, Introduction of Stochastic Processes, Differential Equations. .",
          "url": "https://lucylin1997.github.io/fastpage_copy/about/",
          "relUrl": "/about/",
          "date": ""
      }
      
  

  

  
  

  

  
  

  

  
  

  
  

  
  

  
      ,"page10": {
          "title": "",
          "content": "Sitemap: {{ “sitemap.xml” | absolute_url }} | .",
          "url": "https://lucylin1997.github.io/fastpage_copy/robots.txt",
          "relUrl": "/robots.txt",
          "date": ""
      }
      
  

}